/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfacez;

import Clases.Datos;
import Clases.Utilidades;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class FrmBusquedaProducto extends javax.swing.JDialog {

    private Datos misDatos;
    private DefaultTableModel miTabla;
    private String respuesta = "";

    public void setDatos(Datos misDatos) {
        this.misDatos = misDatos;
    }

    public String getRespuesta() {
        return respuesta;
    }

    private void llenarTabla() {
        String titulos[] = {"ID Producto", "Descripción"};
        String registro[] = new String[4];
        miTabla = new DefaultTableModel(null, titulos);

        if (txtCriterio.getText().equals("")) {
            for (int i = 0; i < misDatos.numeroProductos(); i++) {

                registro[0] = misDatos.getProductos()[i].getIdProducto();
                registro[1] = misDatos.getProductos()[i].getDescripcion();
                miTabla.addRow(registro);
            }
            tblTabla.setModel(miTabla);
            return;
        }

        if (rbtDescripcion.isSelected()) {
            for (int i = 0; i < misDatos.numeroProductos(); i++) {
                if (misDatos.getProductos()[i].getDescripcion().startsWith(txtCriterio.getText())) {
                    registro[0] = misDatos.getProductos()[i].getIdProducto();
                    registro[1] = misDatos.getProductos()[i].getDescripcion();
                    miTabla.addRow(registro);
                }
            }
            tblTabla.setModel(miTabla);
            return;
        }

        if (rbtID.isSelected()) {
            for (int i = 0; i < misDatos.numeroProductos(); i++) {
                if (misDatos.getProductos()[i].getIdProducto().startsWith(txtCriterio.getText())) {
                    registro[0] = misDatos.getProductos()[i].getIdProducto();
                    registro[1] = misDatos.getProductos()[i].getDescripcion();
                    miTabla.addRow(registro);
                }
            }
            tblTabla.setModel(miTabla);
        }

    }

    public FrmBusquedaProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // Agrupamos los botones para que sean excluyentes
        bgrTipoBusqueda.add(rbtID);
        bgrTipoBusqueda.add(rbtDescripcion);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ImgFrmUsuarios/Icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrTipoBusqueda = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        Container = new javax.swing.JLabel();
        Bienvenido = new javax.swing.JLabel();
        Actual = new javax.swing.JLabel();
        Nueva = new javax.swing.JLabel();
        rbtID = new javax.swing.JRadioButton();
        rbtDescripcion = new javax.swing.JRadioButton();
        txtCriterio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();
        btnAceptar = new javax.swing.JToggleButton();
        btnCancelar = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Union = new javax.swing.JLabel();
        Elipse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Búsqueda Productos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFrmBusquedaProductos/2.png"))); // NOI18N
        jPanel2.add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 450, -1));

        Bienvenido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFrmBusquedaProductos/1.jpg"))); // NOI18N
        Bienvenido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(Bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        Actual.setForeground(new java.awt.Color(73, 80, 87));
        Actual.setText("Busqueda por...");
        jPanel2.add(Actual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 20));

        Nueva.setForeground(new java.awt.Color(73, 80, 87));
        Nueva.setText("Busqueda por...");
        jPanel2.add(Nueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, 20));

        rbtID.setSelected(true);
        rbtID.setText("ID Producto");
        rbtID.setContentAreaFilled(false);
        rbtID.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtID.setFocusPainted(false);
        rbtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtIDActionPerformed(evt);
            }
        });
        jPanel2.add(rbtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        rbtDescripcion.setText("Descripción");
        rbtDescripcion.setContentAreaFilled(false);
        rbtDescripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtDescripcion.setFocusPainted(false);
        rbtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtDescripcionActionPerformed(evt);
            }
        });
        jPanel2.add(rbtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        txtCriterio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCriterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCriterioActionPerformed(evt);
            }
        });
        jPanel2.add(txtCriterio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 390, -1));

        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTabla);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 390, 140));

        btnAceptar.setBackground(new java.awt.Color(204, 204, 255));
        btnAceptar.setForeground(new java.awt.Color(0, 0, 0));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(null);
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.setFocusPainted(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 160, 40));

        btnCancelar.setBackground(new java.awt.Color(204, 204, 255));
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 160, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFrmBusquedaProductos/38 (2).png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 140, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 450, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Union.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFrmBusquedaProductos/Union2.png"))); // NOI18N
        jPanel1.add(Union, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        Elipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFrmBusquedaProductos/Ellipse 2093.png"))); // NOI18N
        jPanel1.add(Elipse, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        int num = tblTabla.getRowCount();
        if (num == 0) {
            respuesta = "";
            dispose();
            return;
        }

        for (int i = 0; i < num; i++) {
            if (tblTabla.isRowSelected(i)) {
                respuesta = Utilidades.objectToString(tblTabla.getValueAt(i, 0));
                dispose();
                return;
            }
        }
        respuesta = Utilidades.objectToString(tblTabla.getValueAt(0, 0));
        dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        respuesta = "";
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        llenarTabla();
        txtCriterio.requestFocusInWindow();
    }//GEN-LAST:event_formWindowOpened

    private void rbtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtDescripcionActionPerformed
        txtCriterio.setText("");
        txtCriterio.requestFocusInWindow();
        llenarTabla();
    }//GEN-LAST:event_rbtDescripcionActionPerformed

    private void rbtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtIDActionPerformed
        txtCriterio.setText("");
        txtCriterio.requestFocusInWindow();
        llenarTabla();
    }//GEN-LAST:event_rbtIDActionPerformed

    private void txtCriterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCriterioActionPerformed
        llenarTabla();
    }//GEN-LAST:event_txtCriterioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBusquedaProducto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBusquedaProducto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBusquedaProducto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBusquedaProducto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmBusquedaProducto dialog = new FrmBusquedaProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Actual;
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JLabel Container;
    private javax.swing.JLabel Elipse;
    private javax.swing.JLabel Nueva;
    private javax.swing.JLabel Union;
    private javax.swing.ButtonGroup bgrTipoBusqueda;
    private javax.swing.JToggleButton btnAceptar;
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtDescripcion;
    private javax.swing.JRadioButton rbtID;
    private javax.swing.JTable tblTabla;
    private javax.swing.JTextField txtCriterio;
    // End of variables declaration//GEN-END:variables
}
