/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfacez;

import Clases.Datos;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class FrmCambioClave extends javax.swing.JDialog {

    private String clave;
    private String usuario;
    private Datos misDatos;
     
        public void setDatos(Datos misDatos) {
            this.misDatos = misDatos;
        }
    
        
        public void setUsuario(String usuario) {
            this.usuario = usuario;
        }

    public void setClave(String clave) {
        this.clave = clave;
    }

    public FrmCambioClave(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ImgFrmUsuarios/Icon.png")));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Container = new javax.swing.JLabel();
        Bienvenido = new javax.swing.JLabel();
        Actual = new javax.swing.JLabel();
        txtActual = new javax.swing.JPasswordField();
        Nueva = new javax.swing.JLabel();
        txtNueva = new javax.swing.JPasswordField();
        Confirmacion = new javax.swing.JLabel();
        txtConfirmacion = new javax.swing.JPasswordField();
        btnAceptar = new javax.swing.JToggleButton();
        btnCancelar = new javax.swing.JToggleButton();
        Lock = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsNew/Avatar_Container.png"))); // NOI18N
        jPanel2.add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 450, -1));

        Bienvenido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsNew/Card_Header.jpg"))); // NOI18N
        Bienvenido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(Bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        Actual.setForeground(new java.awt.Color(73, 80, 87));
        Actual.setText("Contraseña actual");
        jPanel2.add(Actual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 20));
        jPanel2.add(txtActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 390, 40));

        Nueva.setForeground(new java.awt.Color(73, 80, 87));
        Nueva.setText("Contraseña nueva");
        jPanel2.add(Nueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 20));
        jPanel2.add(txtNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 390, 40));

        Confirmacion.setForeground(new java.awt.Color(73, 80, 87));
        Confirmacion.setText("Confirmación");
        jPanel2.add(Confirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 20));
        jPanel2.add(txtConfirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 390, 40));

        btnAceptar.setBackground(new java.awt.Color(85, 110, 230));
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(null);
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.setFocusPainted(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 160, 40));

        btnCancelar.setBackground(new java.awt.Color(85, 110, 230));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 160, 40));

        Lock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsNew/Forgot_Password.png"))); // NOI18N
        jPanel2.add(Lock, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 450, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgJDialogCambioClave/Union.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgJDialogCambioClave/Ellipse 209.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String actual = new String(txtActual.getPassword());
        String nueva = new String(txtNueva.getPassword());
        String confirmacion = new String(txtConfirmacion.getPassword());
        if (actual.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar la clave actual");
            txtActual.requestFocusInWindow();
            return;
        }
         if (nueva.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar una nueva clave");
            txtNueva.requestFocusInWindow();
            return;
        }
          if (confirmacion.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar una confirmación de la clave");
            txtConfirmacion.requestFocusInWindow();
            return;
        }
          if (!actual.equals(clave)) {
              JOptionPane.showMessageDialog(rootPane, "La clave no corresponde al usuario ingresado");
              txtActual.setText("");
              txtActual.requestFocusInWindow();
              return;
          }
          if (!nueva.equals(confirmacion)) {
              JOptionPane.showMessageDialog(rootPane, "La clave y la confirmación no corresponden");
              txtActual.setText("");
              txtConfirmacion.setText("");
              txtActual.requestFocusInWindow();
              txtNueva.setText("");
              return;
          }
          
         //Cambiamos la clave
          misDatos.cambioClave(usuario, nueva);
          JOptionPane.showMessageDialog(rootPane, "Clave cambiada correctamente");
          this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCambioClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCambioClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCambioClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCambioClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmCambioClave dialog = new FrmCambioClave(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Actual;
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JLabel Confirmacion;
    private javax.swing.JLabel Container;
    private javax.swing.JLabel Lock;
    private javax.swing.JLabel Nueva;
    private javax.swing.JToggleButton btnAceptar;
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtActual;
    private javax.swing.JPasswordField txtConfirmacion;
    private javax.swing.JPasswordField txtNueva;
    // End of variables declaration//GEN-END:variables
}
