/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfacez;

import Clases.Cliente;
import Clases.Datos;
import Clases.Producto;
import Clases.Usuario;
import Clases.Utilidades;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class FrmClientes extends javax.swing.JInternalFrame {

    private Datos misDatos;
    private int cliAct = 0;
    private boolean nuevo = false;
    private DefaultTableModel miTabla;

    public void setDatos(Datos misDatos) {
        this.misDatos = misDatos;
    }

    public FrmClientes() {
        
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Icon = new javax.swing.JLabel();
        Inventory = new javax.swing.JLabel();
        Frame1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Register = new javax.swing.JLabel();
        Complete = new javax.swing.JLabel();
        txtIDCliente = new javax.swing.JTextField();
        IdPro = new javax.swing.JLabel();
        cmbTipoID = new javax.swing.JComboBox<>();
        Descripcion = new javax.swing.JLabel();
        PrecioJ = new javax.swing.JLabel();
        JIVA = new javax.swing.JLabel();
        jNotas = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnPrimero = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();
        NuevoRegistro = new javax.swing.JLabel();
        Modificar = new javax.swing.JLabel();
        UltimoRegistro = new javax.swing.JLabel();
        Borrar = new javax.swing.JLabel();
        Guardar = new javax.swing.JLabel();
        Buscar = new javax.swing.JLabel();
        Cancelar = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLibro = new javax.swing.JLabel();
        Descripcion1 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        cmbCiudad = new javax.swing.JComboBox<>();
        JIVA1 = new javax.swing.JLabel();
        JIVA4 = new javax.swing.JLabel();
        JIVA2 = new javax.swing.JLabel();
        dchFechaNacimiento = new com.toedter.calendar.JDateChooser();
        dchFechaIngreso = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setTitle("Clientes");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFrmUsuarios/Diseño sin título 1.png"))); // NOI18N
        getContentPane().add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        Inventory.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Inventory.setForeground(new java.awt.Color(255, 255, 255));
        Inventory.setText("Inventory.");
        getContentPane().add(Inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        Frame1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFrmClientes/InventoryFrame2.png"))); // NOI18N
        getContentPane().add(Frame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Register.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Register.setForeground(new java.awt.Color(0, 0, 0));
        Register.setText("¡Registre los clientes!");
        jPanel1.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        Complete.setForeground(new java.awt.Color(134, 146, 166));
        Complete.setText("Complete la informacion de sus clientes.");
        jPanel1.add(Complete, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        txtIDCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtIDCliente.setEnabled(false);
        jPanel1.add(txtIDCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 190, 40));

        IdPro.setForeground(new java.awt.Color(134, 146, 166));
        IdPro.setText("ID Cliente *");
        jPanel1.add(IdPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        cmbTipoID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Cedula Ciudadania", "NIT", "Tarjeta Identidad", "Registro Civil", "Cédula Extranjería", "Pasaporte" }));
        cmbTipoID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmbTipoID.setEnabled(false);
        jPanel1.add(cmbTipoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 180, 40));

        Descripcion.setForeground(new java.awt.Color(134, 146, 166));
        Descripcion.setText("Dirección");
        jPanel1.add(Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        PrecioJ.setForeground(new java.awt.Color(134, 146, 166));
        PrecioJ.setText("Nombres *");
        jPanel1.add(PrecioJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, -1));

        JIVA.setForeground(new java.awt.Color(134, 146, 166));
        JIVA.setText("Tipo de identificación *");
        jPanel1.add(JIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jNotas.setForeground(new java.awt.Color(134, 146, 166));
        jNotas.setText("Apellidos *");
        jPanel1.add(jNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        txtNombres.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNombres.setEnabled(false);
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 200, 40));

        txtApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtApellidos.setEnabled(false);
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 190, 40));

        jLabel11.setForeground(new java.awt.Color(134, 146, 166));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Primer Registro");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 90, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/cancelar 1.png"))); // NOI18N
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setEnabled(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 600, 60, 60));

        btnPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/023-folder 1.png"))); // NOI18N
        btnPrimero.setBorder(null);
        btnPrimero.setBorderPainted(false);
        btnPrimero.setContentAreaFilled(false);
        btnPrimero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrimero.setFocusPainted(false);
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrimero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 70, 50));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/003-add 1.png"))); // NOI18N
        btnNuevo.setBorder(null);
        btnNuevo.setBorderPainted(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.setFocusPainted(false);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 100, 70));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/010-time 1.png"))); // NOI18N
        btnModificar.setBorder(null);
        btnModificar.setBorderPainted(false);
        btnModificar.setContentAreaFilled(false);
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.setFocusPainted(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 110, 50));

        btnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/012-check 1.png"))); // NOI18N
        btnUltimo.setBorder(null);
        btnUltimo.setBorderPainted(false);
        btnUltimo.setContentAreaFilled(false);
        btnUltimo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUltimo.setFocusPainted(false);
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });
        jPanel1.add(btnUltimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 90, 50));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/018-tick mark 1_1.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setEnabled(false);
        btnGuardar.setFocusPainted(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, 90, 60));

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/037-remove 1.png"))); // NOI18N
        btnBorrar.setBorder(null);
        btnBorrar.setBorderPainted(false);
        btnBorrar.setContentAreaFilled(false);
        btnBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrar.setFocusPainted(false);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, 90, 60));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/045-third quarter 1.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setFocusPainted(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, 100, 60));

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/anterior 1.png"))); // NOI18N
        btnAnterior.setBorder(null);
        btnAnterior.setBorderPainted(false);
        btnAnterior.setContentAreaFilled(false);
        btnAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnterior.setFocusPainted(false);
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 40, 50));

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/anterior 2.png"))); // NOI18N
        btnSiguiente.setBorder(null);
        btnSiguiente.setBorderPainted(false);
        btnSiguiente.setContentAreaFilled(false);
        btnSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSiguiente.setFocusPainted(false);
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 630, 50, 50));

        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 610, 130));

        NuevoRegistro.setForeground(new java.awt.Color(134, 146, 166));
        NuevoRegistro.setText("Nuevo Registro");
        jPanel1.add(NuevoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 100, -1));

        Modificar.setForeground(new java.awt.Color(134, 146, 166));
        Modificar.setText("Modificar");
        jPanel1.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 570, 70, -1));

        UltimoRegistro.setForeground(new java.awt.Color(134, 146, 166));
        UltimoRegistro.setText("Ultimo Registro");
        jPanel1.add(UltimoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, -1, -1));

        Borrar.setForeground(new java.awt.Color(134, 146, 166));
        Borrar.setText("Borrar contenido");
        jPanel1.add(Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 570, 100, -1));

        Guardar.setForeground(new java.awt.Color(134, 146, 166));
        Guardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Guardar.setText("Guardar");
        jPanel1.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 660, 100, -1));

        Buscar.setForeground(new java.awt.Color(134, 146, 166));
        Buscar.setText("Buscar");
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 660, 60, -1));

        Cancelar.setForeground(new java.awt.Color(134, 146, 166));
        Cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cancelar.setText("Cancelar");
        jPanel1.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 660, 60, -1));

        txtDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDireccion.setEnabled(false);
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 180, 40));

        jLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFrmClientes/It Girl (1).png"))); // NOI18N
        jPanel1.add(jLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 150, 100));

        Descripcion1.setForeground(new java.awt.Color(134, 146, 166));
        Descripcion1.setText("Telefono");
        jPanel1.add(Descripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        txtTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTelefono.setEnabled(false);
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 200, 40));

        cmbCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Cali Valle del Cauca", "Aguachica Cesar", "Apartadó Antioquia", "Arauca", "Armenia Quindío", "Barrancabermeja Santander", "Barranquilla Atlántico", "Bello Antioquia", "Bogotá Distrito Capital", "Bucaramanga Santander", "Buenaventura Valle del Cauca", "Buga Valle del Cauca", "Cartago Valle del Cauca", "Cartagena Bolívar", "Caucasia Antioquia", "Chia Cundinamarca", "Ciénaga Magdalena", "Cúcuta Norte de Santander", "Dosquebradas Risaralda", "Duitama Boyacá", "Envigado Antioquia", "Facatativá Cundinamarca", "Florencia Caqueta", "Floridablanca Santander", "Fusagasugá Cundinamarca", "Girardot Cundinamarca", "Girón Santander", "bagué Tolima", "Ipiales Nariño", "Itagüí Antioquia", "Jamundí Valle del Cauca", "Lorica Córdoba", "Los Patios Norte de Santander", "Magangué Bolivar", "Maicao Guajira", "Malambo Atlántico", "Manizales Caldas", "Medellín Antioquia", "Melgar Tolima", "Montería Córdoba", "Neiva Huila", "Ocaña Norte de Santander", "Paipa, Boyacá", "Palmira Valle del Cauca", "Pamplona Norte de Santander", "Pasto Nariño", "Pereira Risaralda", "Piedecuesta Santander", "Pitalito Huila", "Popayán Cauca", "Quibdó Choco", "Riohacha Guajira", "Rionegro Antioquia", "Sabanalarga Atlántico", "Sahagún Córdoba", "San Andrés Isla", "Santa Marta Magdalena", "Sincelejo Sucre", "Soacha Cundinamarca", "Sogamoso Boyacá", "Soledad Atlántico", "Tibú Norte de Santander", "Tuluá Valle del Cauca", "Tumaco Nariño", "Tunja Boyacá", "Turbo Antioquia", "Valledupar Cesar", "Villa de leyva", "Villa del Rosario Norte de Santander", "Villavicencio Meta", "Yopal Casanare", "Yumbo Valle del Cauca", "Zipaquirá Cundinamarca" }));
        cmbCiudad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmbCiudad.setEnabled(false);
        jPanel1.add(cmbCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 190, 40));

        JIVA1.setForeground(new java.awt.Color(134, 146, 166));
        JIVA1.setText("Ciudad");
        jPanel1.add(JIVA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        JIVA4.setForeground(new java.awt.Color(134, 146, 166));
        JIVA4.setText("Fecha ingreso");
        jPanel1.add(JIVA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));

        JIVA2.setForeground(new java.awt.Color(134, 146, 166));
        JIVA2.setText("Fecha Nacimiento");
        jPanel1.add(JIVA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        dchFechaNacimiento.setEnabled(false);
        jPanel1.add(dchFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 180, 40));

        dchFechaIngreso.setEnabled(false);
        jPanel1.add(dchFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 200, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 780, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
//
        // Habilita los botones
        btnPrimero.setEnabled(false);
        btnAnterior.setEnabled(false);
        btnSiguiente.setEnabled(false);
        btnUltimo.setEnabled(false);
        btnNuevo.setEnabled(false);
        btnModificar.setEnabled(false);
        btnBorrar.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnCancelar.setEnabled(true);

        // Habilita los campos
        txtIDCliente.setEnabled(true);
        cmbTipoID.setEnabled(true);
        txtNombres.setEnabled(true);
        txtApellidos.setEnabled(true);
        txtDireccion.setEnabled(true);
        txtTelefono.setEnabled(true);
        cmbCiudad.setEnabled(true);
        dchFechaNacimiento.setEnabled(true);
        // dchFechaIngreso.setEnabled(true);

        // Limpiar campos
        txtIDCliente.setText("");
        cmbTipoID.setSelectedIndex(0);
        txtNombres.setText("");
        txtApellidos.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        cmbCiudad.setSelectedIndex(0);
        dchFechaNacimiento.setDate(new Date());
        dchFechaIngreso.setDate(new Date());

        // Activamos el flag de registro nuevo
        nuevo = true;

        // Damos foco al campo ID
        txtIDCliente.requestFocusInWindow();


    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        // Validaciones
        if (txtIDCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar un ID");
            txtIDCliente.requestFocusInWindow();
            return;
        }

        if (cmbTipoID.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un tipo de identificación");
            cmbTipoID.requestFocusInWindow();
            return;
        }

        if (txtNombres.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar un nombre(s)");
            txtNombres.requestFocusInWindow();
            return;
        }

        if (txtApellidos.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar un apellido(s)");
            txtApellidos.requestFocusInWindow();
            return;
        }

        if (dchFechaNacimiento.getDate().after(new Date())) {
            JOptionPane.showMessageDialog(rootPane,
                    "La fecha de nacimiento debe ser anterior a la fecha actual");
            txtNombres.requestFocusInWindow();
            return;
        }

        // Si es nuevo validamos qu el cliente no exista
        int pos = misDatos.posicionCliente(txtIDCliente.getText());
        if (nuevo) {
            if (pos != -1) {
                JOptionPane.showMessageDialog(rootPane, "Cliente ya existente");
                txtIDCliente.requestFocusInWindow();
                return;
            }
        } else {

            if (pos == -1) {
                JOptionPane.showMessageDialog(rootPane, "Cliente no existe");
                txtIDCliente.requestFocusInWindow();
                return;
            }

        }

        // Creamos el objeto producto y lo agregamos a datos
        Cliente miCliente = new Cliente(
                txtIDCliente.getText(),
                cmbTipoID.getSelectedIndex(),
                txtNombres.getText(),
                txtApellidos.getText(),
                txtDireccion.getText(),
                txtTelefono.getText(),
                cmbCiudad.getSelectedIndex(),
                dchFechaNacimiento.getDate(),
                dchFechaIngreso.getDate());

        String msg;
        if (nuevo) {
            msg = misDatos.agregarCliente(miCliente);
        } else {
            msg = misDatos.modificarCliente(miCliente, pos);
        }

        JOptionPane.showMessageDialog(rootPane, msg);

        // Deshabilita los botones
        btnPrimero.setEnabled(true);
        btnAnterior.setEnabled(true);
        btnSiguiente.setEnabled(true);
        btnUltimo.setEnabled(true);
        btnNuevo.setEnabled(true);
        btnModificar.setEnabled(true);
        btnBorrar.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(false);

        // Deshabilita los campos
        txtIDCliente.setEnabled(false);
        cmbTipoID.setEnabled(false);
        txtNombres.setEnabled(false);
        txtApellidos.setEnabled(false);
        txtDireccion.setEnabled(false);
        txtTelefono.setEnabled(false);
        cmbCiudad.setEnabled(false);
        dchFechaNacimiento.setEnabled(false);
        dchFechaIngreso.setEnabled(false);

        //Actualizar cambios en tabla
        llenarTabla();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        // Deshabilita los botones
        btnPrimero.setEnabled(true);
        btnAnterior.setEnabled(true);
        btnSiguiente.setEnabled(true);
        btnUltimo.setEnabled(true);
        btnNuevo.setEnabled(true);
        btnModificar.setEnabled(true);
        btnBorrar.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(false);

        // Deshabilita los campos
        txtIDCliente.setEnabled(false);
        cmbTipoID.setEnabled(false);
        txtNombres.setEnabled(false);
        txtApellidos.setEnabled(false);
        txtDireccion.setEnabled(false);
        txtTelefono.setEnabled(false);
        cmbCiudad.setEnabled(false);
        dchFechaNacimiento.setEnabled(false);
        dchFechaIngreso.setEnabled(false);


    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        // Habilita los botones
        btnPrimero.setEnabled(false);
        btnAnterior.setEnabled(false);
        btnSiguiente.setEnabled(false);
        btnUltimo.setEnabled(false);
        btnNuevo.setEnabled(false);
        btnModificar.setEnabled(false);
        btnBorrar.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnCancelar.setEnabled(true);

        // Habilita los campos
        cmbTipoID.setEnabled(true);
        txtNombres.setEnabled(true);
        txtApellidos.setEnabled(true);
        txtDireccion.setEnabled(true);
        txtTelefono.setEnabled(true);
        cmbCiudad.setEnabled(true);
        dchFechaNacimiento.setEnabled(true);

        // Desactivamos el flag de registro nuevo
        nuevo = false;

        // Damos foco al campo ID
        cmbTipoID.requestFocusInWindow();

    }//GEN-LAST:event_btnModificarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        mostrarRegistro();
        llenarTabla();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        cliAct = 0;
        mostrarRegistro();
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        cliAct = misDatos.numeroClientes() - 1;
        mostrarRegistro();
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        cliAct++;
        if (cliAct == misDatos.numeroClientes()) {
            cliAct = 0;
        }
        mostrarRegistro();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        cliAct--;
        if (cliAct == -1) {
            cliAct = misDatos.numeroClientes() - 1;
        }

        mostrarRegistro();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed

        int rta = JOptionPane.showConfirmDialog(rootPane, "¿Esta seguro de borrar el registro?");
        if (rta != 0) {
            return;
        }
        String msg;
        msg = misDatos.borrarCliente(cliAct);
        JOptionPane.showMessageDialog(rootPane, msg);
        cliAct = 0;
        mostrarRegistro();

        //Actualizar cambios en tabla
        llenarTabla();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String cliente = JOptionPane.showInputDialog("Ingrese codigo de cliente");
        if (cliente.equals("")) {
            return;
        }
        int pos = misDatos.posicionCliente(cliente);
        if (pos == -1) {
            JOptionPane.showMessageDialog(rootPane, "Cliente no existente");
            return;
        }
        cliAct = pos;
        mostrarRegistro();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void mostrarRegistro() {
        txtIDCliente.setText(misDatos.getClientes()[cliAct].getIdCliente());
        cmbTipoID.setSelectedIndex(misDatos.getClientes()[cliAct].getIdTipo());
        txtNombres.setText("" + misDatos.getClientes()[cliAct].getNombres());
        txtApellidos.setText(misDatos.getClientes()[cliAct].getApellidos());
        txtDireccion.setText(misDatos.getClientes()[cliAct].getDireccion());
        txtTelefono.setText(misDatos.getClientes()[cliAct].getTelefono());
        cmbCiudad.setSelectedIndex(misDatos.getClientes()[cliAct].getIdCiudad());
        dchFechaNacimiento.setDate(misDatos.getClientes()[cliAct].getFechaNacimiento());
        dchFechaIngreso.setDate(misDatos.getClientes()[cliAct].getFechaIngreso());
    }

    private void llenarTabla() {
        String titulos[] = {"ID Cliente", "Tipo ID", "Nombres", "Apellidos", "Dirección", "Telefono",
            "Ciudad", "F.Nacimiento", "F.Ingreso"};
        String registro[] = new String[9];
        miTabla = new DefaultTableModel(null, titulos);
        for (int i = 0; i < misDatos.numeroClientes(); i++) {
            registro[0] = misDatos.getClientes()[i].getIdCliente();
            registro[1] = tipoID(misDatos.getClientes()[i].getIdTipo());
            registro[2] = misDatos.getClientes()[i].getNombres();
            registro[3] = misDatos.getClientes()[i].getDireccion();
            registro[4] = misDatos.getClientes()[i].getApellidos();
            registro[5] = misDatos.getClientes()[i].getTelefono();
            registro[6] = ciudad(misDatos.getClientes()[i].getIdCiudad());
            registro[7] = "" + misDatos.getClientes()[i].getFechaNacimiento();
            registro[8] = "" + misDatos.getClientes()[i].getFechaIngreso();

            miTabla.addRow(registro);
        }
        tblTabla.setModel(miTabla);
    }

    private String tipoID(int id) {
        switch (id) {
            case 1:
                return "Cedula Ciudadania";
            case 2:
                return "NIT";
            case 3:
                return "Tarjeta Identidad";
            case 4:
                return "Registro Civil";
            case 5:
                return "Cedula Extrajería";
            case 6:
                return "Pasaporte";
            default:
                return "No definido";
        }

    }

    private String ciudad(int id) {
        switch (id) {

            case 1:
                return "Cali Valle del Cauca";
            case 2:
                return "Apartadó Antioquia";
            case 3:
                return "Barrancabermeja Santander";
            case 4:
                return "Armenia Quindío";
            case 5:
                return "Barranquilla Atlántico";
            case 6:
                return "Bello Antioquia";
            case 7:
                return "Bogotá Distrito Capital";
            case 8:
                return "Bucaramanga Santander";
            case 9:
                return "Buenaventura Valle del Cauca";
            case 10:
                return "Buga Valle del Cauca";
            case 11:
                return "Aguachica Cesar";
            case 12:
                return "Cartago Valle del Cauca";
            case 13:
                return "Cartagena Bolívar";
            case 14:
                return "Caucasia Antioquia";
            case 15:
                return "Cereté Córdoba";
            case 16:
                return "Chia Cundinamarca";
            case 17:
                return "Ciénaga Magdalena";
            case 18:
                return "Cúcuta Norte de Santander";
            case 19:
                return "Dosquebradas Risaralda";
            case 20:
                return "Duitama Boyacá";
            case 21:
                return "Envigado Antioquia";
            case 22:
                return "Facatativá Cundinamarca";
            case 23:
                return "Florencia Caqueta";
            case 24:
                return "Floridablanca Santander";
            case 25:
                return "Fusagasugá Cundinamarca";
            case 26:
                return "Girardot Cundinamarca";
            case 27:
                return "Girón Santander";
            case 28:
                return "Ibagué Tolima";
            case 29:
                return "Ipiales Nariño";
            case 30:
                return "Itagüí Antioquia";
            case 31:
                return "Jamundí Valle del Cauca";
            case 32:
                return "Lorica Córdoba";
            case 33:
                return "Los Patios Norte de Santander";
            case 34:
                return "Magangué Bolivar";
            case 35:
                return "Maicao Guajira";
            case 36:
                return "Malambo Atlántico";
            case 37:
                return "Manizales Caldas";
            case 38:
                return "Medellín Antioquia";
            case 39:
                return "Melgar Tolima";
            case 40:
                return "Montería Córdoba";
            case 41:
                return "Neiva Huila";
            case 42:
                return "Ocaña Norte de Santander";
            case 43:
                return "Palmira Valle del Cauca";
            case 44:
                return "Pamplona Norte de Santander";
            case 45:
                return "Pasto Nariño";
            case 46:
                return "Pereira Risaralda";
            case 47:
                return "Piedecuesta Santander";
            case 48:
                return "Pitalito Huila";
            case 49:
                return "Popayán Cauca";
            case 50:
                return "Quibdó Choco";
            case 51:
                return "Riohacha Guajira";
            case 52:
                return "Rionegro Antioquia";
            case 53:
                return "Sabanalarga Atlántico";
            case 54:
                return "Sahagún Córdoba";
            case 55:
                return "San Andrés Isla";
            case 56:
                return "Santa Marta Magdalena";
            case 57:
                return "Soacha Cundinamarca";
            case 58:
                return "Sogamoso Boyacá";
            case 59:
                return "Soledad Atlántico";
            case 60:
                return "Tibú Norte de Santander";
            case 61:
                return "Tuluá Valle del Cauca";
            case 62:
                return "Tumaco Nariño";
            case 63:
                return "Tunja Boyacá";
            case 64:
                return "Turbo Antioquia";
            case 65:
                return "Valledupar Cesar";
            case 66:
                return "Villa de leyva";
            case 67:
                return "Villa del Rosario Norte de Santander";
            case 68:
                return "Villavicencio Meta";
            case 69:
                return "Yopal Casanare";
            case 70:
                return "Yumbo Valle del Cauca";
            case 71:
                return "Zipaquirá Cundinamarca";

            default:
                return "No definido";
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Borrar;
    private javax.swing.JLabel Buscar;
    private javax.swing.JLabel Cancelar;
    private javax.swing.JLabel Complete;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Descripcion1;
    private javax.swing.JLabel Frame1;
    private javax.swing.JLabel Guardar;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel IdPro;
    private javax.swing.JLabel Inventory;
    private javax.swing.JLabel JIVA;
    private javax.swing.JLabel JIVA1;
    private javax.swing.JLabel JIVA2;
    private javax.swing.JLabel JIVA4;
    private javax.swing.JLabel Modificar;
    private javax.swing.JLabel NuevoRegistro;
    private javax.swing.JLabel PrecioJ;
    private javax.swing.JLabel Register;
    private javax.swing.JLabel UltimoRegistro;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JComboBox<String> cmbCiudad;
    private javax.swing.JComboBox<String> cmbTipoID;
    private com.toedter.calendar.JDateChooser dchFechaIngreso;
    private com.toedter.calendar.JDateChooser dchFechaNacimiento;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLibro;
    private javax.swing.JLabel jNotas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTabla;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIDCliente;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
