/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfacez;

import Clases.Datos;
import Clases.Opcion;
import Clases.Utilidades;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Date;
import javax.swing.JOptionPane;
//import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
//import sun.swing.table.DefaultTableCellHeaderRenderer;




public class FrmFactura extends javax.swing.JInternalFrame {

    private Datos misDatos;
    private DefaultTableModel miTabla;

    public void setDatos(Datos misDatos) {
        this.misDatos = misDatos;
    }

    public FrmFactura() {
        initComponents();
       // setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ImgFrmUsuarios/Icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Icon = new javax.swing.JLabel();
        Inventory = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Register = new javax.swing.JLabel();
        Complete = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();
        PrecioJ = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        cmbProducto = new javax.swing.JComboBox<>();
        cmbCliente = new javax.swing.JComboBox<>();
        btnBuscarCliente = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        txtTotalCantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTotalValor = new javax.swing.JTextField();
        btnGrabar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEliminarTodo = new javax.swing.JButton();
        Printer = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        btnBuscarProducto = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Nueva Factura");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFrmUsuarios/Diseño sin título 1.png"))); // NOI18N
        getContentPane().add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        Inventory.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Inventory.setForeground(new java.awt.Color(255, 255, 255));
        Inventory.setText("Inventory.");
        getContentPane().add(Inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 64, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFrmFacturas/Facturas.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(134, 146, 166));
        jLabel2.setText("Fecha");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        Register.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Register.setForeground(new java.awt.Color(0, 0, 0));
        Register.setText("¡Registre una factura!");
        jPanel1.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        Complete.setForeground(new java.awt.Color(134, 146, 166));
        Complete.setText("Complete la informacion de las facturas.");
        jPanel1.add(Complete, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        Descripcion.setForeground(new java.awt.Color(134, 146, 166));
        Descripcion.setText("Cliente");
        jPanel1.add(Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        PrecioJ.setForeground(new java.awt.Color(134, 146, 166));
        PrecioJ.setText("Producto");
        jPanel1.add(PrecioJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setEnabled(false);
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 200, 40));

        cmbProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cmbProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 190, 40));

        cmbCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cmbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 200, 40));

        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFrmFacturas/Lupa.png"))); // NOI18N
        btnBuscarCliente.setToolTipText("Busca un cliente");
        btnBuscarCliente.setBorder(null);
        btnBuscarCliente.setBorderPainted(false);
        btnBuscarCliente.setContentAreaFilled(false);
        btnBuscarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCliente.setFocusPainted(false);
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 220, 40, 60));
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 200, 40));

        jLabel3.setForeground(new java.awt.Color(134, 146, 166));
        jLabel3.setText("Cantidad");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDetalle);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 620, 180));

        txtTotalCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalCantidad.setEnabled(false);
        jPanel1.add(txtTotalCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 620, 150, 40));

        jLabel4.setForeground(new java.awt.Color(134, 146, 166));
        jLabel4.setText("Totales");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 590, -1, -1));

        txtTotalValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalValor.setEnabled(false);
        jPanel1.add(txtTotalValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 620, 150, 40));

        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/018-tick mark 1_1.png"))); // NOI18N
        btnGrabar.setToolTipText("Grabar todo");
        btnGrabar.setBorder(null);
        btnGrabar.setBorderPainted(false);
        btnGrabar.setContentAreaFilled(false);
        btnGrabar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGrabar.setFocusPainted(false);
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 60, 70));

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/003-add 1.png"))); // NOI18N
        btnAdicionar.setToolTipText("Agregar");
        btnAdicionar.setBorder(null);
        btnAdicionar.setBorderPainted(false);
        btnAdicionar.setContentAreaFilled(false);
        btnAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionar.setFocusPainted(false);
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 60, 70));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/037-remove 1.png"))); // NOI18N
        btnEliminar.setToolTipText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setFocusPainted(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 60, 70));

        btnEliminarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/016-delete 1.png"))); // NOI18N
        btnEliminarTodo.setToolTipText("Borrar todo");
        btnEliminarTodo.setBorder(null);
        btnEliminarTodo.setBorderPainted(false);
        btnEliminarTodo.setContentAreaFilled(false);
        btnEliminarTodo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarTodo.setFocusPainted(false);
        btnEliminarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTodoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 60, 70));

        Printer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFrmFacturas/Printer.png"))); // NOI18N
        jPanel1.add(Printer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 460, 160));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsNew/Coding (1).png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 340, 150));

        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusPainted(false);
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 60, 60));

        btnBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFrmFacturas/Lupa.png"))); // NOI18N
        btnBuscarProducto.setToolTipText("Busca un producto");
        btnBuscarProducto.setBorder(null);
        btnBuscarProducto.setBorderPainted(false);
        btnBuscarProducto.setContentAreaFilled(false);
        btnBuscarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarProducto.setFocusPainted(false);
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 40, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 780, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

        //Cargamos clientes
        Opcion opc = new Opcion("NA", "Seleccione un cliente...");
        cmbCliente.addItem(opc);
        for (int i = 0; i < misDatos.numeroClientes(); i++) {
            opc = new Opcion(
                    misDatos.getClientes()[i].getIdCliente(),
                    misDatos.getClientes()[i].getNombres() + " "
                    + misDatos.getClientes()[i].getApellidos());
            cmbCliente.addItem(opc);
        }

        //Cargamos Productos
        opc = new Opcion("NA", "Seleccione un producto...");
        cmbProducto.addItem(opc);
        for (int i = 0; i < misDatos.numeroProductos(); i++) {
            opc = new Opcion(
                    misDatos.getProductos()[i].getIdProducto(),
                    misDatos.getProductos()[i].getDescripcion());
            cmbProducto.addItem(opc);
        }

        // Colocamos fecha del sistema
        txtFecha.setText(Utilidades.formatDate(new Date()));

        // Mostramos totales en cero
        txtTotalCantidad.setText("0");
        txtTotalValor.setText("0");

        //Formateamos la tabla
        llenarTabla();
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameActivated

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        if (cmbProducto.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane,
                    "Debe selecciónar un producto");
            cmbProducto.requestFocusInWindow();
            return;
        }

        if (txtCantidad.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane,
                    "Debe digitar una cantidad");
            txtCantidad.requestFocusInWindow();
            return;
        }

        if (!Utilidades.isNumeric(txtCantidad.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un valor numerico");
            txtCantidad.setText("");
            txtCantidad.requestFocusInWindow();
            return;
        }

        int cantidad = Integer.parseInt(txtCantidad.getText());

        if (cantidad <= 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un mayor que 0");
            txtCantidad.requestFocusInWindow();
            return;
        }

        //Buscamos los datos del producto seleccionado
        int pos = misDatos.posicionProducto(((Opcion) cmbProducto.getSelectedItem()).getValor());

        // Adicionamos producto a la tabla
        String registro[] = new String[5];
        registro[0] = misDatos.getProductos()[pos].getIdProducto();
        registro[1] = misDatos.getProductos()[pos].getDescripcion();
        registro[2] = "" + misDatos.getProductos()[pos].getPrecio();
        registro[3] = "" + cantidad;
        registro[4] = "" + cantidad * (misDatos.getProductos()[pos].getPrecio());
        miTabla.addRow(registro);

        //Inicializamos campos
        cmbProducto.setSelectedIndex(0);
        txtCantidad.setText("");
        cmbProducto.requestFocusInWindow();

        // Actualizamos totales
        totales();

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed

        if (cmbCliente.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane,
                    "Debe selecciónar un cliente");
            cmbCliente.requestFocusInWindow();
            return;
        }

        int totCan = new Integer(txtTotalCantidad.getText());

        if (totCan == 0) {
            JOptionPane.showMessageDialog(rootPane,
                    "Debe ingresar detalle de la factura");
            cmbProducto.requestFocusInWindow();
            return;
        }

        int rta = JOptionPane.showConfirmDialog(rootPane, "¿Esta seguro de grabar esta factura?");
        if (rta != 0) {
            return;
        }

        // Adicionamos un consecutivo a la factura
        int numFac = misDatos.getNumFac() + 1;

        //Grabamos factura
        FileWriter fw = null;
        PrintWriter pw = null;
        try {
            fw = new FileWriter("Data/facturas.txt", true);
            pw = new PrintWriter(fw);

            // Encabezado de factura
            String aux = "1|"
                    + numFac + "|"
                    + ((Opcion) cmbCliente.getSelectedItem()).getValor() + "|"
                    + ((Opcion) cmbCliente.getSelectedItem()).getDescripcion() + "|"
                    + txtFecha.getText();
            pw.println(aux);

            // Detalle de factura
            int num = tblDetalle.getRowCount();
            for (int i = 0; i < num; i++) {
                aux = "2|"
                        + Utilidades.objectToString(tblDetalle.getValueAt(i, 0)) + "|"
                        + Utilidades.objectToString(tblDetalle.getValueAt(i, 1)) + "|"
                        + Utilidades.objectToString(tblDetalle.getValueAt(i, 2)) + "|"
                        + Utilidades.objectToString(tblDetalle.getValueAt(i, 3)) + "|"
                        + Utilidades.objectToString(tblDetalle.getValueAt(i, 4));
                pw.println(aux);
            }
        } catch (Exception e1) {
            e1.printStackTrace();
        } finally {
            try {
                if (fw != null) {
                    fw.close();
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }

        JOptionPane.showMessageDialog(rootPane,
                "Factura: " + numFac + " generada con exito");
        misDatos.setNumFac(numFac);

        // Inicalizamos campos
        cmbCliente.setSelectedIndex(0);
        limpiarTabla();
        totales();
        cmbCliente.requestFocusInWindow();
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnEliminarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTodoActionPerformed
        int rta = JOptionPane.showConfirmDialog(rootPane, "¿Esta seguro de borrar el detalle de la factura");
        if (rta != 0) {
            return;
        }
        limpiarTabla();
        totales();
    }//GEN-LAST:event_btnEliminarTodoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        if (cmbProducto.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane,
                    "Debe selecciónar un producto");
            cmbProducto.requestFocusInWindow();
            return;
        }

        try {
            DefaultTableModel modelo = (DefaultTableModel) tblDetalle.getModel();
            int filas = tblDetalle.getRowCount();
            for (int i = 0; filas > i; i++) {
                String idTabla = Utilidades.objectToString(tblDetalle.getValueAt(i, 0));
                String idCombo = ((Opcion) cmbProducto.getSelectedItem()).getValor();
                if (idTabla.equals(idCombo)) {
                    modelo.removeRow(i);
                    //Actualizamos totales totales
                    totales();
                    return;
                }
                //modelo.removeRow(0);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        FrmBusquedaCliente miBusqueda = new FrmBusquedaCliente(null, closable);
        miBusqueda.setDatos(misDatos);
        miBusqueda.setLocationRelativeTo(null);
        miBusqueda.setVisible(true);
        String rta = miBusqueda.getRespuesta();
        JOptionPane.showMessageDialog(rootPane, rta);
        if(rta.equals("")) {
            return;
        }
        for(int i = 0; i < cmbCliente.getItemCount(); i++) {
            if(((Opcion)cmbCliente.getItemAt(i)).getValor().equals(rta)) {
                cmbCliente.setSelectedIndex(i);
                return;
            }
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        
        FrmBusquedaProducto miBusqueda = new FrmBusquedaProducto(null, closable);
        miBusqueda.setDatos(misDatos);
        miBusqueda.setLocationRelativeTo(null);
        miBusqueda.setVisible(true);
        String rta = miBusqueda.getRespuesta();
        JOptionPane.showMessageDialog(rootPane, rta);
        if(rta.equals("")) {
            return;
        }
        for(int i = 0; i < cmbProducto.getItemCount(); i++) {
            if(((Opcion)cmbProducto.getItemAt(i)).getValor().equals(rta)) {
                cmbProducto.setSelectedIndex(i);
                return;
            }
        }
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Complete;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel Inventory;
    private javax.swing.JLabel PrecioJ;
    private javax.swing.JLabel Printer;
    private javax.swing.JLabel Register;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarTodo;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JComboBox<Object> cmbCliente;
    private javax.swing.JComboBox<Object> cmbProducto;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDetalle;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtTotalCantidad;
    private javax.swing.JTextField txtTotalValor;
    // End of variables declaration//GEN-END:variables

    private void llenarTabla() {
        String titulos[] = {"ID Producto", "Descripción", "Precio", "Cantidad", "Valor"};
        miTabla = new DefaultTableModel(null, titulos);
        tblDetalle.setModel(miTabla);

        // Alinear campos numericos a la derecha
//        DefaultTableCellHeaderRenderer tcr = new DefaultTableCellHeaderRenderer();
//        tcr.setHorizontalAlignment(SwingConstants.RIGHT);
//        tblDetalle.getColumnModel().getColumn(2).setCellRenderer(tcr);
//        tblDetalle.getColumnModel().getColumn(3).setCellRenderer(tcr);
//        tblDetalle.getColumnModel().getColumn(4).setCellRenderer(tcr);
    }

    private void totales() {
        int num = tblDetalle.getRowCount();
        int sumCan = 0, sumVal = 0;
        for (int i = 0; i < num; i++) {
            sumCan += Utilidades.objectToInt(tblDetalle.getValueAt(i, 3));
            sumVal += Utilidades.objectToInt(tblDetalle.getValueAt(i, 4));
        }
        txtTotalCantidad.setText("" + sumCan);
        txtTotalValor.setText("" + sumVal);
    }

    public void limpiarTabla() {
        try {
            DefaultTableModel modelo = (DefaultTableModel) tblDetalle.getModel();
            int filas = tblDetalle.getRowCount();
            for (int i = 0; filas > i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
