/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfacez;

import Clases.Datos;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class FrmLogin extends javax.swing.JFrame {

        private Datos misDatos;
        
        public void setDatos(Datos misDatos) {
            this.misDatos = misDatos;
        }
    
    public FrmLogin() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ImgFrmUsuarios/Icon.png")));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Icon = new javax.swing.JLabel();
        JUsuario = new javax.swing.JLabel();
        JContraseña = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        Recuerdame = new javax.swing.JCheckBox();
        btnIniciar = new javax.swing.JToggleButton();
        Forgot = new javax.swing.JButton();
        Lock = new javax.swing.JLabel();
        CardHeader = new javax.swing.JLabel();
        Tarjet = new javax.swing.JLabel();
        FondoWhite = new javax.swing.JLabel();
        Elipse = new javax.swing.JLabel();
        DeibyRayoCC = new javax.swing.JLabel();
        Union = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFrmLogin/Avatar_Container.png"))); // NOI18N
        jPanel1.add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        JUsuario.setForeground(new java.awt.Color(73, 80, 87));
        JUsuario.setText("Usuario");
        jPanel1.add(JUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        JContraseña.setForeground(new java.awt.Color(73, 80, 87));
        JContraseña.setText("Contraseña");
        jPanel1.add(JContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
        jPanel1.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 390, 40));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 390, 40));

        Recuerdame.setForeground(new java.awt.Color(73, 80, 87));
        Recuerdame.setText("Recuerdame");
        Recuerdame.setBorder(null);
        Recuerdame.setContentAreaFilled(false);
        Recuerdame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Recuerdame.setFocusPainted(false);
        jPanel1.add(Recuerdame, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        btnIniciar.setBackground(new java.awt.Color(85, 110, 230));
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("Iniciar sesión");
        btnIniciar.setBorder(null);
        btnIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 390, 40));

        Forgot.setForeground(new java.awt.Color(116, 120, 141));
        Forgot.setText("¿Olvidaste la contraseña?");
        Forgot.setBorder(null);
        Forgot.setBorderPainted(false);
        Forgot.setContentAreaFilled(false);
        Forgot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Forgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgotActionPerformed(evt);
            }
        });
        jPanel1.add(Forgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 190, 20));

        Lock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFrmLogin/Lock1.png"))); // NOI18N
        jPanel1.add(Lock, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 20, -1));

        CardHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFrmLogin/Card_Content.png"))); // NOI18N
        jPanel1.add(CardHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        Tarjet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFrmLogin/Card_Header.jpg"))); // NOI18N
        jPanel1.add(Tarjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 450, 490));

        FondoWhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFrmLogin/Union.png"))); // NOI18N
        getContentPane().add(FondoWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        Elipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFrmLogin/Ellipse 209.png"))); // NOI18N
        getContentPane().add(Elipse, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, 380, 270));

        DeibyRayoCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DeibyRayo/Copyright_Container.png"))); // NOI18N
        getContentPane().add(DeibyRayoCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 620, -1, -1));

        Union.setForeground(new java.awt.Color(60, 63, 65));
        Union.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFrmLogin/Sign in.png"))); // NOI18N
        getContentPane().add(Union, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ForgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ForgotActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        
        //Validar el usuario que esta almacenado en la clase Datos
        
        if (!misDatos.validarUsuario(txtUsuario.getText(), new String (txtClave.getPassword() ))) {
            JOptionPane.showMessageDialog(rootPane, "Usuario o clave incorrecto");
            txtUsuario.setText("");
            txtClave.setText("");
            txtUsuario.requestFocus();
            return;
        }
        
        //Si el usuario es correcto entre a la ventada principal
        FrmPrincipal miPrincipal = new FrmPrincipal();
        this.setVisible(false);
        miPrincipal.setDatos(misDatos);
        miPrincipal.setPerfil(misDatos.getPerfil(txtUsuario.getText()));
         miPrincipal.setClave(new String (txtClave.getPassword() ));
         miPrincipal.setUsuario(txtUsuario.getText());
        //miPrincipal.setExtendedState(JFrame.MAXIMIZED_BOTH);
        miPrincipal.setVisible(true);
        
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CardHeader;
    private javax.swing.JLabel DeibyRayoCC;
    private javax.swing.JLabel Elipse;
    private javax.swing.JLabel FondoWhite;
    private javax.swing.JButton Forgot;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel JContraseña;
    private javax.swing.JLabel JUsuario;
    private javax.swing.JLabel Lock;
    private javax.swing.JCheckBox Recuerdame;
    private javax.swing.JLabel Tarjet;
    private javax.swing.JLabel Union;
    private javax.swing.JToggleButton btnIniciar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
