/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfacez;

import Clases.Datos;
import Clases.Producto;
import Clases.Usuario;
import Clases.Utilidades;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class FrmProductos extends javax.swing.JInternalFrame {

    private Datos misDatos;
    private int proAct = 0;
    private boolean nuevo = false;
    private DefaultTableModel miTabla;

    public void setDatos(Datos misDatos) {
        this.misDatos = misDatos;
    }

    public FrmProductos() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Icon = new javax.swing.JLabel();
        Inventory = new javax.swing.JLabel();
        Frame1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Register = new javax.swing.JLabel();
        Complete = new javax.swing.JLabel();
        txtIDProducto = new javax.swing.JTextField();
        IdPro = new javax.swing.JLabel();
        cmbIVA = new javax.swing.JComboBox<>();
        Descripcion = new javax.swing.JLabel();
        PrecioJ = new javax.swing.JLabel();
        JIVA = new javax.swing.JLabel();
        jNotas = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtNota = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnPrimero = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();
        NuevoRegistro = new javax.swing.JLabel();
        Modificar = new javax.swing.JLabel();
        UltimoRegistro = new javax.swing.JLabel();
        Borrar = new javax.swing.JLabel();
        Guardar = new javax.swing.JLabel();
        Buscar = new javax.swing.JLabel();
        Cancelar = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLibro = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Productos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFrmUsuarios/Diseño sin título 1.png"))); // NOI18N
        getContentPane().add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        Inventory.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Inventory.setForeground(new java.awt.Color(255, 255, 255));
        Inventory.setText("Inventory.");
        getContentPane().add(Inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        Frame1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFrmProductos/Frame 3.png"))); // NOI18N
        getContentPane().add(Frame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Register.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Register.setForeground(new java.awt.Color(0, 0, 0));
        Register.setText("¡Registre los productos!");
        jPanel1.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        Complete.setForeground(new java.awt.Color(134, 146, 166));
        Complete.setText("Complete la informacion de los productos.");
        jPanel1.add(Complete, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        txtIDProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtIDProducto.setEnabled(false);
        txtIDProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDProductoActionPerformed(evt);
            }
        });
        jPanel1.add(txtIDProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 200, 40));

        IdPro.setForeground(new java.awt.Color(134, 146, 166));
        IdPro.setText("ID Producto *");
        jPanel1.add(IdPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        cmbIVA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "0%", "10%", "16%" }));
        cmbIVA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmbIVA.setEnabled(false);
        jPanel1.add(cmbIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 200, 40));

        Descripcion.setForeground(new java.awt.Color(134, 146, 166));
        Descripcion.setText("Descripción *");
        jPanel1.add(Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        PrecioJ.setForeground(new java.awt.Color(134, 146, 166));
        PrecioJ.setText("Precio *");
        jPanel1.add(PrecioJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        JIVA.setForeground(new java.awt.Color(134, 146, 166));
        JIVA.setText("IVA *");
        jPanel1.add(JIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jNotas.setForeground(new java.awt.Color(134, 146, 166));
        jNotas.setText("Notas");
        jPanel1.add(jNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        txtPrecio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPrecio.setEnabled(false);
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 170, 40));

        txtNota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNota.setEnabled(false);
        jPanel1.add(txtNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 200, 40));

        jLabel11.setForeground(new java.awt.Color(134, 146, 166));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Primer Registro");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 90, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/cancelar 1.png"))); // NOI18N
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setEnabled(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, 60, 60));

        btnPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/023-folder 1.png"))); // NOI18N
        btnPrimero.setBorder(null);
        btnPrimero.setBorderPainted(false);
        btnPrimero.setContentAreaFilled(false);
        btnPrimero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrimero.setFocusPainted(false);
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrimero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, -1, 50));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/003-add 1.png"))); // NOI18N
        btnNuevo.setBorder(null);
        btnNuevo.setBorderPainted(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.setFocusPainted(false);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 100, 70));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/010-time 1.png"))); // NOI18N
        btnModificar.setBorder(null);
        btnModificar.setBorderPainted(false);
        btnModificar.setContentAreaFilled(false);
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.setFocusPainted(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 110, 50));

        btnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/012-check 1.png"))); // NOI18N
        btnUltimo.setBorder(null);
        btnUltimo.setBorderPainted(false);
        btnUltimo.setContentAreaFilled(false);
        btnUltimo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUltimo.setFocusPainted(false);
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });
        jPanel1.add(btnUltimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 90, 50));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/018-tick mark 1_1.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setEnabled(false);
        btnGuardar.setFocusPainted(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 590, 90, 60));

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/037-remove 1.png"))); // NOI18N
        btnBorrar.setBorder(null);
        btnBorrar.setBorderPainted(false);
        btnBorrar.setContentAreaFilled(false);
        btnBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrar.setFocusPainted(false);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, 90, 60));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/045-third quarter 1.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setFocusPainted(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 590, 100, 60));

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/anterior 1.png"))); // NOI18N
        btnAnterior.setBorder(null);
        btnAnterior.setBorderPainted(false);
        btnAnterior.setContentAreaFilled(false);
        btnAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnterior.setFocusPainted(false);
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 40, 50));

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsGenerales/anterior 2.png"))); // NOI18N
        btnSiguiente.setBorder(null);
        btnSiguiente.setBorderPainted(false);
        btnSiguiente.setContentAreaFilled(false);
        btnSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSiguiente.setFocusPainted(false);
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 630, 50, 50));

        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 620, 150));

        NuevoRegistro.setForeground(new java.awt.Color(134, 146, 166));
        NuevoRegistro.setText("Nuevo Registro");
        jPanel1.add(NuevoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 100, -1));

        Modificar.setForeground(new java.awt.Color(134, 146, 166));
        Modificar.setText("Modificar");
        jPanel1.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 70, -1));

        UltimoRegistro.setForeground(new java.awt.Color(134, 146, 166));
        UltimoRegistro.setText("Ultimo Registro");
        jPanel1.add(UltimoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, -1, -1));

        Borrar.setForeground(new java.awt.Color(134, 146, 166));
        Borrar.setText("Borrar contenido");
        jPanel1.add(Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 560, 100, -1));

        Guardar.setForeground(new java.awt.Color(134, 146, 166));
        Guardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Guardar.setText("Guardar");
        jPanel1.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 650, 100, -1));

        Buscar.setForeground(new java.awt.Color(134, 146, 166));
        Buscar.setText("Buscar");
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 650, 60, -1));

        Cancelar.setForeground(new java.awt.Color(134, 146, 166));
        Cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cancelar.setText("Cancelar");
        jPanel1.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 650, 60, -1));

        txtDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDescripcion.setEnabled(false);
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 200, 40));

        jLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFrmProductos/Group 49 (2).png"))); // NOI18N
        jPanel1.add(jLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 780, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
//
        // Habilita los botones
        btnPrimero.setEnabled(false);
        btnAnterior.setEnabled(false);
        btnSiguiente.setEnabled(false);
        btnUltimo.setEnabled(false);
        btnNuevo.setEnabled(false);
        btnModificar.setEnabled(false);
        btnBorrar.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnCancelar.setEnabled(true);

        // Habilita los campos
        txtIDProducto.setEnabled(true);
        txtNota.setEnabled(true);
        txtPrecio.setEnabled(true);
        txtDescripcion.setEnabled(true);
        cmbIVA.setEnabled(true);

        // Limpiar campos
        txtIDProducto.setText("");
        txtNota.setText("");
        txtPrecio.setText("");
        txtDescripcion.setText("");
        txtIDProducto.setText("");
        cmbIVA.setSelectedIndex(0);

        // Activamos el flag de registro nuevo
        nuevo = true;

        // Damos foco al campo ID
        txtIDProducto.requestFocusInWindow();


    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        // Validaciones
        if (txtIDProducto.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar un ID");
            txtIDProducto.requestFocusInWindow();
            return;
        }
        
        if (txtDescripcion.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar una descripción");
            txtDescripcion.requestFocusInWindow();
            return;
        }
        
        if (txtPrecio.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un precio");
            txtPrecio.requestFocusInWindow();
            return;
        }
        
        if (!Utilidades.isNumeric(txtPrecio.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un valor numerico");
            txtPrecio.requestFocusInWindow();
            return;
        }
        
        int precio = Integer.parseInt(txtPrecio.getText());
        
         if (precio <= 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un mayor que 0");
            txtPrecio.requestFocusInWindow();
            return;
        }

        // Si es nuevo validamos qu el usuario no exista
        int pos = misDatos.posicionProducto(txtIDProducto.getText());
        if (nuevo) {
            if (pos != -1) {
                JOptionPane.showMessageDialog(rootPane, "Producto ya existente");
                txtIDProducto.requestFocusInWindow();
                return;
            }
        } else {

            if (pos == -1) {
                JOptionPane.showMessageDialog(rootPane, "Producto no existe");
                txtIDProducto.requestFocusInWindow();
                return;
            }

        }

        // Creamos el objeto producto y lo agregamos a datos
        Producto miProducto = new Producto(
                txtIDProducto.getText(),
                txtDescripcion.getText(),
                precio,
                cmbIVA.getSelectedIndex(),
                txtNota.getText());

        String msg;
        if (nuevo) {
            msg = misDatos.agregarProducto(miProducto);
        } else {
            msg = misDatos.modificarProducto(miProducto, pos);
        }

        JOptionPane.showMessageDialog(rootPane, msg);

        // Deshabilita los botones
        btnPrimero.setEnabled(true);
        btnAnterior.setEnabled(true);
        btnSiguiente.setEnabled(true);
        btnUltimo.setEnabled(true);
        btnNuevo.setEnabled(true);
        btnModificar.setEnabled(true);
        btnBorrar.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(false);

        // Deshabilita los campos
        txtIDProducto.setEnabled(false);
        txtDescripcion.setEnabled(false);
        txtPrecio.setEnabled(false);
        txtNota.setEnabled(false);
        cmbIVA.setEnabled(false);

        //Actualizar cambios en tabla
        llenarTabla();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        // Deshabilita los botones
        btnPrimero.setEnabled(true);
        btnAnterior.setEnabled(true);
        btnSiguiente.setEnabled(true);
        btnUltimo.setEnabled(true);
        btnNuevo.setEnabled(true);
        btnModificar.setEnabled(true);
        btnBorrar.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(false);

        // Deshabilita los campos
        txtIDProducto.setEnabled(false);
        txtDescripcion.setEnabled(false);
        txtPrecio.setEnabled(false);
        txtNota.setEnabled(false);
        cmbIVA.setEnabled(false);

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        // Habilita los botones
        btnPrimero.setEnabled(false);
        btnAnterior.setEnabled(false);
        btnSiguiente.setEnabled(false);
        btnUltimo.setEnabled(false);
        btnNuevo.setEnabled(false);
        btnModificar.setEnabled(false);
        btnBorrar.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnCancelar.setEnabled(true);

        // Habilita los campos
        txtDescripcion.setEnabled(true);
        txtPrecio.setEnabled(true);
        txtNota.setEnabled(true);
        cmbIVA.setEnabled(true);

        // Desactivamos el flag de registro nuevo
        nuevo = false;

        // Damos foco al campo ID
        txtDescripcion.requestFocusInWindow();

    }//GEN-LAST:event_btnModificarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        mostrarRegistro();
        llenarTabla();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        proAct = 0;
        mostrarRegistro();
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        proAct = misDatos.numeroProductos() - 1;
        mostrarRegistro();
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        proAct++;
        if (proAct == misDatos.numeroProductos()) {
            proAct = 0;
        }
        mostrarRegistro();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        proAct--;
        if (proAct == -1) {
            proAct = misDatos.numeroProductos() - 1;
        }

        mostrarRegistro();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed

        int rta = JOptionPane.showConfirmDialog(rootPane, "¿Esta seguro de borrar el registro?");
        if (rta != 0) {
            return;
        }
        String msg;
        msg = misDatos.borrarProducto(proAct);
        JOptionPane.showMessageDialog(rootPane, msg);
        proAct = 0;
        mostrarRegistro();

        //Actualizar cambios en tabla
        llenarTabla();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String producto = JOptionPane.showInputDialog("Ingrese codigo de producto");
        if (producto.equals("")) {
            return;
        }
        int pos = misDatos.posicionProducto(producto);
        if (pos == -1) {
            JOptionPane.showMessageDialog(rootPane, "Producto no existente");
            return;
        }
        proAct = pos;
        mostrarRegistro();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtIDProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDProductoActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void mostrarRegistro() {
        txtIDProducto.setText(misDatos.getProductos()[proAct].getIdProducto());
        txtDescripcion.setText(misDatos.getProductos()[proAct].getDescripcion());
        txtPrecio.setText("" + misDatos.getProductos()[proAct].getPrecio());
        txtNota.setText(misDatos.getProductos()[proAct].getNota());
        cmbIVA.setSelectedIndex(misDatos.getProductos()[proAct].getIva());
    }

    private void llenarTabla() {
        String titulos[] = {"ID Producto", "Descripción", "Precio", "IVA", "Notas"};
        String registro[] = new String[5];
        miTabla = new DefaultTableModel(null, titulos);
        for (int i = 0; i < misDatos.numeroProductos(); i++) {
            registro[0] = misDatos.getProductos()[i].getIdProducto();
            registro[1] = misDatos.getProductos()[i].getDescripcion();
            registro[2] = "" + misDatos.getProductos()[i].getPrecio();
            registro[3] = iva(misDatos.getProductos()[i].getIva());
            registro[4] = misDatos.getProductos()[i].getNota();
            miTabla.addRow(registro);
        }
        tblTabla.setModel(miTabla);
    }

    private String iva(int idIVA) {
       switch(idIVA) {
           case 0: return "0%";
           case 1: return "10%";
           case 2: return "16%";
           default: return "No definido";
       }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Borrar;
    private javax.swing.JLabel Buscar;
    private javax.swing.JLabel Cancelar;
    private javax.swing.JLabel Complete;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Frame1;
    private javax.swing.JLabel Guardar;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel IdPro;
    private javax.swing.JLabel Inventory;
    private javax.swing.JLabel JIVA;
    private javax.swing.JLabel Modificar;
    private javax.swing.JLabel NuevoRegistro;
    private javax.swing.JLabel PrecioJ;
    private javax.swing.JLabel Register;
    private javax.swing.JLabel UltimoRegistro;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JComboBox<String> cmbIVA;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLibro;
    private javax.swing.JLabel jNotas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTabla;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIDProducto;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
